### ISSUE TITLE
Tests unitaire Animation classe Bomb

### ISSUE THREAD

**Issue by tonyop62** [TL1-fa17/projet1#10]
Je n'arrive pas à créer les tests de le classe Bomb car la plupart de mes fonctions utilisent l'animation.
Les tests ne fonctionnent pas car il faut OpenGL pour les classes Image et SpriteSheet. J'ai essayé la méthode addFrame(int duration, int x, int y) de Animation pour justement éviter d'utiliser Image et SpriteSheetmais rien n'y fait.
Selon : https://github.com/TL1-fa17/projet1/commit/55f42717e56a78b19ac90b6142cbead9a8a1fcc6#commitcomment-9860158 mais je ne vois pas comment faire pour tester les méthodes de la classe Bombe sans Image et SpriteSheet.

**Comment by cedricmorin1** [comment]
Hello la team pour la superBomb il y a un bug je ne sais pas si vous l'avais vue mais elle n'explose plus. 
Et dite @tonyop62 @fcrombecque @Calooe  que fait-on maintenant ? ou plutôt qui est en train de faire quoi ? 
Merci c'est pour voir ce que je peux prendre maintenant que tout est ok

**Comment by fcrombecque** [comment]
Salut, j'ai ajouté le son pour les bombes, j'essaye de corriger les bug entre le son bombe et background.

**Comment by Calooe** [comment]
La SuperBomb n'explose plus ! @tonyop62

**Comment by tonyop62** [comment]
yop c ma faute désolé j'ai fini la bombe mais pas la superbombe j'ai fait des modifs sur la bombe pour que les tests unitaires fonctionnent mais pas sur superbombe ca sera réglé dans peu de temps sinon cedric il faudrait une fenêtre au démarrage pour dire le nombre de bombes des joueurs ou des truc du genre

**Comment by cedricmorin1** [comment]
D'accord @tonyop62 je m'occupe de ça je créer une issue pour cela. Comme ça tout ce qui concernera la fenêtre sera dedans 
Ps: je commencerai la fenêtre demain

**Comment by tonyop62** [comment]
Tests unitaires et bombes fonctionnent correctement
