### ISSUE TITLE
Lancement de 2 sons en parallele

### ISSUE THREAD

**Issue by fcrombecque** [TL1-fa17/projet1#12]
J'ai des petits soucis à laisser la musique pendant le son d'explosion de la bombe.

J'ai lu sur le net qu'il n'était pas possible de faire du multithread avec Slick 2D ?

Je continue mes recherches. Si quelqu'un à une idée je suis preneur !

**Comment by tonyop62** [comment]
essaie d'arreter le son principal quand tu lance le son de la bombe et relance le quand le son de la bombe est fini si le multithread est impossible

**Comment by fcrombecque** [comment]
Oki merci, je vais faire ça.
