### ISSUE TITLE
Classe WindowGame

### ISSUE THREAD

**Issue by tonyop62** [TL1-fa17/projet1#16]
Est-ce que quelqu'un se sert encore de WindowGame ? Pourrais-je avoir la réponse de tout le monde SVP. Je voudrais la supprimer.

**Comment by Calooe** [comment]
@tonyop62 Je n'utilise plus ! Donc c'est ok pour moi :+1:

**Comment by fcrombecque** [comment]
@tonyop62   Je ne l'utilise plus non plus.

**Comment by tonyop62** [comment]
ok merci les gars! and the last ?

**Comment by cedricmorin1** [comment]
the last to remove this class ;)
