### ISSUE TITLE
Nouveau bug bombe

### ISSUE THREAD

**Issue by tonyop62** [TL1-fa17/projet1#18]
Nouveau bug trouvé : lorsque le monstre est touché une fois par une bombe, il ne peut plus l'être.

**Comment by tonyop62** [comment]
Gros changement possible : 
On admet que la bombe peut faire des dégats sur n'importe qui et peu importe celui qui l'a posée. Donc je me demandais si la bombe ne devrait pas être un objet moins dépendant de l'avatar ? c'est à dire qu'il n'aurait plus d'attribut bombe ou superbombe.

**Comment by cedricmorin1** [comment]
qui est ce qui n'aurai plus l'attribut bombe ou superbombe l'avatar ?

**Comment by tonyop62** [comment]
oui

**Comment by cedricmorin1** [comment]
Bah comment tu dira que la bombe la appartient à l'avatar tel. et lui dire l'avatar tel peut avoir autant de bombe a part le mettre dans le constructeur avatar ?

**Comment by tonyop62** [comment]
ben il suffit de laisser l'attribut nbSuperBombe et c'est ok. Et limite on s'en moque de savoir si la bombe appartient à l'avatar si elle peut toucher tout le monde même l'avatar lui-même

**Comment by cedricmorin1** [comment]
Pour lui attribuer des points car si par la suite on a le temps de faire du multi je verrai bien un compteur de point que si un avatar touche un autre avatar a autant de point et pareil pour monstre. Comme ça la partit durera un certain temps et à la fin du temps lui qui a le plus de points à gagner

**Comment by tonyop62** [comment]
il faudrait plutôt prendre l'inverse car la bombe peut toucher tout le monde. C'est celui qui a le moins été touché qui gagne la partie. Parce la ça sert à rien vu qu'un avatar peut se faire toucher par ses propres bombes, dans ce cas il ne faut pas qu'il se fasse toucher par ses bombes là ça serait logique si c'est celui qui a le plus touché l'adversaire qui gagne.

**Comment by cedricmorin1** [comment]
Oui au pire ont peux faire ça. 
Mais il faudra faire aussi quand un monstre touche un joueur il "prend des points" comme quand un joueur ce fait toucher par une bombe

**Comment by tonyop62** [comment]
donc un monstre peut gagner la partie en muiltijoueur ?

**Comment by cedricmorin1** [comment]
Non mdr. 
Je t'appel sur le numéro d'hier ?

**Comment by tonyop62** [comment]
non je peux pas là

**Comment by cedricmorin1** [comment]
Bon je vais faire court: 
-Un joueur prend des points lorsqu'il se fait toucher par une bombe 
-Un joueur prend des points lorsqu'il se fait toucher par un monstre
-Un monstre peut mourir lorsqu'il se fait toucher par une bombe mais ne prend aucun points 
Le joueur qui a le moins de points à la fin d'une partit gagne
Dit moi ce que tu en pense

**Comment by tonyop62** [comment]
oui c'est ce que je dis depuis tout à l'heure donc ça sert à rien qu'une bombe appartienne à un avatar

**Comment by cedricmorin1** [comment]
Bah oui mdr Relit la discussion tu va comprendre pourquoi je dit ça ^^
Bref si c'est ça oui, mais serieusement pourquoi le sortir de l'avatar puisque actuellement ça fonctionne qu'un avatar peut ce faire toucher par sa propre bombe ?

**Comment by tonyop62** [comment]
ben je trouve ça pas très logique qu'un avatar à un attribut bombe et un attribut superbombe alors que la bombe peut le toucher. Si la bombe peut le toucher cela veut que une fois qu'elle est posée elle complètement indépendante du joueur, le joueur ne peut plus agir dessus ou faire quoi que ce soit avec, elle a sa propre vie en gros. Le joueur n'est la que pour lui dire ou se poser. Ce n'est pas  "SA" bombe à l'avatar.

**Comment by cedricmorin1** [comment]
Oui je voie.

**Comment by tonyop62** [comment]
Pouvez-vous me donner votre avis aussi parce que ça va faire un gros changement dans le code je pense si on fait comme ça

**Comment by Calooe** [comment]
Je suis d'accord @tonyop62 :+1:

**Comment by tonyop62** [comment]
tout le monde est ok car je sais pas combien de temps ça va prendre cette modif ?

**Comment by fcrombecque** [comment]
Juste pour savoir, il est impératif de savoir à qui appartient une bombe non?

**Comment by fcrombecque** [comment]
Comment tu calcul qui peut poser une bombe?

**Comment by tonyop62** [comment]
il est pas imperatif de savoir ki a posé la bombe car elle attaque tout le monde. et il suffira de dire au joueur que s il a pose une bombe il attende que la bombe qu'il a posé doit exploser avant d'en reposer une graca a un booléen

**Comment by fcrombecque** [comment]
Oki, c'est bon pour moi.
On part sur le principe que les personnages ne pourront pas poser plusieurs bombes dans ce cas?

**Comment by tonyop62** [comment]
oui comme ca c'est l'avatar qui n'a pas le droit de poser une bombe et non la bombe qui n'a pas le droit de se poser si il y en a deja une

**Comment by cdlm** [comment]
enfin, des discussions sur le code métier :+1:

**Comment by tonyop62** [comment]
Attention ! ça y est la bombe n'appartient plus à l'avatar. De gros changements sont à prendre en compte. les tests ne sont pas encore faits et il y a quelques bugs à résoudre mais la logique générale est là.

**Comment by tonyop62** [comment]
Les tests sont faits
