### ISSUE TITLE
Barre de vie. Who ?

### ISSUE THREAD

**Issue by tonyop62** [TL1-fa17/projet1#19]
Qui voudrait faire une barre de vie pour les personnages ?

**Comment by cedricmorin1** [comment]
Je galere déjà avec le menu moi --" 
Et la c'est en pause jusqu'a mardi je bosser trop sur le projet par rapport à l'autre court j'ai pris du retard faut que je rattrape ça

**Comment by Calooe** [comment]
Présent !

**Comment by tonyop62** [comment]
ok issue close
