### ISSUE TITLE
Définir les éléments principaux du projet

### ISSUE THREAD

**Issue by cdlm** [TL1-fa17/projet1#2]
Faites un cahier des charges rapide dans le fichier README:
- une idée du type de jeu
- les éléments principaux (avatar, obstacles, niveaux…)
- les interactions entre ces éléments

**Comment by cedricmorin1** [comment]
— Type de jeu, ont c’était convenu ensemble d’un Bomberman. 
— Je pense que l’on devrait faire un 1 VS 1 avec des fantômes pour commencer et ensuite si le temps nous le permet faire un 1 vs 1 mais en « réseaux »
— les interactions sont entre les deux joueurs, les bombes posées par les joueurs, les fantômes et les briques fixes et « cassables ». 
À votre disposition pour plus d'informations. 
Ps: François, Anthony, Vincent n'hésiter pas à completer si vous pensais qu'ils manques des choses.

**Comment by cdlm** [comment]
J'attire votre attention sur le fait que toute tâche va prendre bien plus de temps que vous le pensez (même sans prendre en compte la [Loi de Hofstadter](http://fr.wikipedia.org/wiki/Loi_de_Hofstadter), les surprises techniques sont amplement suffisantes).

Un premier jalon réaliste est de créer un projet Slick2D avec une classe minimale, et de vous assurer que cela se lance. Ensuite, expérimenter avec les primitives graphiques et des animations simples. Vous pouvez parcourir [ce tutoriel](http://www.shionn.org/tutoriels-slick-2d), il n'a pas l'air mal. Si vous pouvez avoir jeté un œil à tout ça d'ici mardi, ça serait bien.

**Comment by cdlm** [comment]
Projet terminé
