### ISSUE TITLE
Impossible de lancer le code 

### ISSUE THREAD

**Issue by cedricmorin1** [TL1-fa17/projet1#25]
Hello la Team pourquoi je ne peux plus lancer le code
voila l'erreur 
Erreur : impossible de trouver ou charger la classe principale uvinfo.bomberman.GameServer

**Comment by cedricmorin1** [comment]
Je précise je suis sur master et je lance bien mainScreenGameState ;)

**Comment by tonyop62** [comment]
GameServer fait parti de le branche c'est bizarre ça

**Comment by cedricmorin1** [comment]
It's ok ;) eclipse enregistre les run et à pris un ancien run
