### ISSUE TITLE
Beug d'ajout image fond de carte

### ISSUE THREAD

**Issue by cedricmorin1** [TL1-fa17/projet1#5]
Hello, 
Les images pour le fond de carte ne fonctionne pas et donc nous met dans un java.lang.runTimeException. 
J'ai regarder c'est parce que le dossier images  n'est pas dans les ressources. Il faudrait je pense utilisé le tutoriel de slik2D visible ici http://www.shionn.org/slick2d-lesson-2-map-display
Est ce que la personne qui la fait voudrais repasser avec ça ou je peux le faire ?

**Comment by Calooe** [comment]
La ça passe chez moi j'ai juste modifié le passe des PNG dans "terrain2.tmx" car un .tmx est associé a un PNG

**Comment by cedricmorin1** [comment]
Le soucis ne ce passe pas la chez moi c'est juste qu'il n'arrive pas a trouver le dossier où sont situé les images. 
Je ne comprend pas pourquoi ils n'ont pas étaient mise dans un dossier dans le projet ? 
Pourquoi les mettre en dehors ?

**Comment by Calooe** [comment]
Si si cest dedans je viens de puller javais lerreur ! jai corrigé et commit& push, ca devrait etre bon la

**Comment by cedricmorin1** [comment]
Bah non toujours dans un dossier res en dehors du projet. 
Il faudrait pensais à le mettre dans le projet. 
Cela a t-il était fait avec le tuto slik2D ?

**Comment by Calooe** [comment]
Oui antho a suivi le tuto de Slick a la lettre. t'as essayé de Pull le projet ?

**Comment by cedricmorin1** [comment]
![capture d ecran 2015-02-17 a 22 42 44](https://cloud.githubusercontent.com/assets/10976562/6237828/64553bfe-b6f6-11e4-9f0b-f916c1e19b4b.png)
![capture d ecran 2015-02-17 a 22 43 05](https://cloud.githubusercontent.com/assets/10976562/6237833/666bd452-b6f6-11e4-8387-25994c0c35ee.png)
Voila deux captures d'écran la première est la dernière fusion faite la seconde le résultat de eclipse. 
Soit c'est moi  qui ne sais pas le faire fonctionné soit c'est vraiment que le dossier res n'est pas dans le projet car après quand je regard dans le dossier git il est bien dedans mais en dehors du projet

**Comment by cdlm** [comment]
Comme on dit, chezmoiçamarche™. Le plus probable est qu'il faut que tu rafraîchisse (F5) le projet dans eclipse.

**Comment by cedricmorin1** [comment]
Bon ce n'était pas une question de rafraîchissement, mais plus une histoire qu'il ne se met pas dans le projet. 
J'ai déplacé "a la main" le dossier d'image dans le projet et maintenant tout fonctionne. 
Attention donc pour la suite du projet lorsqu'il y aura des soucis d'accès aux images .
Je ferme cette issue :)

**Comment by cedricmorin1** [comment]
Ps: je ne voie pas où fermer l'issue ^^
