### ISSUE TITLE
Information Tâches

### ISSUE THREAD

**Issue by cedricmorin1** [TL1-fa17/projet1#6]
Hello, 
Par contre il faudrait que vous vous mettiez dans les issues "taches" que le profs a fait car par exemple vincent tu ne t'y était pas mis pour l'avatar et ont a fait le même boulot (un peu bête tout de même) 
Et vincent pourquoi quand je prend ton projet j'ai bien tout mais des que je veux bouger ton dragon il me kill mon programme ?

**Comment by fcrombecque** [comment]
Salut,

Tu peux essayer de le récupérer la.
Normalement ça doit fonctionner

**Comment by cedricmorin1** [comment]
Tout est récupérer. Mais cela ne fonctionne pas j'ai toujours la fenêtre qui se kill des lorsque j'appuie sur une flèche.

**Comment by Calooe** [comment]
Cest bon la normalement. Mais ya un soucis, des que le Drag arrive dans un mur, plus moyen de le deplacer

**Comment by cedricmorin1** [comment]
Toujours pas de mon coté ... Fenêtre qui ce kill des que j'appuie sur une flèche

**Comment by Calooe** [comment]
J'ai push ya 4 minutes. en ce qui concerne les taches jai pas l'issue de @cdlm . je veux bien que l'on s'accorde sur qui fait quoi ! [ par exemple m'ocupper de l'avatar ;) ]

**Comment by cedricmorin1** [comment]
Oui j'ai pris ton dernier push de 15h36 et toujours le même résultat. 
Je veux bien tenté de faire les tests mais pour cela il faut que ça fonctionne de mon coté

**Comment by Calooe** [comment]
ça doit être le même soucis qu'hier, Refresh et re-pull !

**Comment by cedricmorin1** [comment]
Non le soucis d'hier n'était pas ça je l'ai écrit sur l'ancienne issue à quoi c'était du

**Comment by fcrombecque** [comment]
ça marche en effet, ça marche même un peu trop loin !

**Comment by cedricmorin1** [comment]
Bon tout est bon pour moi merci :)
