### ISSUE TITLE
AvatarTest

### ISSUE THREAD

**Issue by cedricmorin1** [TL1-fa17/projet1#8]
Hello les gens, je m'occupe des tests unitaires de la classe Avatar
Par contre lorsque je créer un avatar  (Avatar drag = new Avatar();) il me l'accept pas dans le test pourtant comme le constructeur de Avatar ne prend pas de paramètre c'est comme ça qu'il faut le faire ou y a t-il une chose subtile derrière à savoir ? 
Merci

**Comment by cedricmorin1** [comment]
Bonjour monsieur @cdlm , 
Pour les test unitaire y a t-il besoin de tester des getter ? 
Merci

**Comment by Calooe** [comment]
@cedricmorin1 il faut ajouter "throws SlickException" à la suite de ta méthode contenant le new: 

==> void InstanciationPersonnage() throws SlickException {...}

**Comment by cedricmorin1** [comment]
C'est déjà fait vas voir je l'ai pusher

**Comment by cdlm** [comment]
Pas la peine pour les accesseurs

**Comment by cedricmorin1** [comment]
D'accord je l'avais fait donc ils seront en commentaire. 
Par contre nous avons un beug concernant le test je ne voie pas du tout pourquoi et même en mode debug. Je vais pusher d'ici 2 mins les tests unitaires de la classe Avatar @Calooe peut tu me dire si il y à une chose spécial à faire comme c'est toi qui à fait cette classe et si non @cdlm pourra t-on voir qu'elle est le soucis mardi pour ne pas que l'on le reproduire 
Merci

**Comment by cdlm** [comment]
Ne laissez pas de code en commentaire, c'est juste du bruit.

Pour le bug de lancement des tests, si c'est de l'erreur `No OpenGL context…` qu'il s'agit, elle disparait en commentant la construction du `SpriteSheet` dans le constructeur de `Avatar`. Ce qui suggère que vous ne pouvez pas appeler certaines parties de Slick2D depuis les tests, car elles nécessitent qu'OpenGL soit chargé et initialisé. Ça n'est pas grave, de toute façon c'est très difficile de tester la partie graphique autrement qu'à la main. Il faut juste réorganiser le code de pour que vos tests n'exercent pas de code graphique.

**Comment by cedricmorin1** [comment]
D'accord j'ai supprimé les lignes de code en commentaire.

Pour le bug j'ai bien compris alors merci
